---
title: "Extract_EnvirCovar_BB_BE"
author: "Caro Scholz"
date: "3 9 2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exploring and Preparing Metabarcoding data

R version: 3.5.3

### Packages
```{r}
library(dplyr)
library(raster)
library(sf)
library(readr)
```


### Workspace
```{r}
WorkDir <- here::here()#getwd()
rawdata_wd <- file.path(WorkDir, "2_data/geo_data")
procdata_wd <- file.path(WorkDir, "6_processed_data")
```


### Load data from foxes
```{r}
foxsample_data <- readRDS(paste0(procdata_wd, "/sampledata_richness.rds"))
foxsample_data

str(foxsample_data)
foxsample_data$lat <- as.numeric(foxsample_data$lat)

fox_sp <- st_as_sf(foxsample_data, coords = c("long", "lat"), crs = 4236) %>%
  st_transform(crs = 3035)

# tmap_mode("view")
# tm_shape(fox_sp) +
#   tm_dots(col = "area")

```

### Load Environmental variables
```{r}
tree_cover <- raster(paste0(rawdata_wd, "/tcd_bb_mv_b_20m_3035.tif")) 
tree_cover <- clamp(tree_cover, upper = 200, useValues = FALSE)

imperv <- raster(paste0(rawdata_wd, "/imp_bb_mv_b_20m_3035.tif"))
imperv <- clamp(imperv, upper = 200, useValues = FALSE)

human_fpi <- raster(paste0(rawdata_wd, "/HFP2009_int_3035.tif"))
#human_fpi <- clamp(human_fpi, upper = 200, useValues = FALSE)
```



## extract environmental values

```{r}
fox_sp <- fox_sp %>%
   dplyr::select(IZW_ID, sex)


BE_BB_envcov <- extract(tree_cover, as_Spatial(fox_sp), buffer = 1000,
                        fun = mean, na.rm = T, sp = T)
BE_BB_envcov2 <- extract(imperv, BE_BB_envcov, buffer = 1000,
                         fun = mean, na.rm = T, sp = T)
BE_BB_alldata <- extract(human_fpi, BE_BB_envcov2, buffer = 1000,
                         fun = mean, na.rm = T, sp = T)


fox_variables <- as.data.frame(BE_BB_alldata)
colnames(fox_variables)[3:5] <- c("tree_cover_1000m", "imperv_new_1000m",
                                  "human_fpi_1000m")
fox_variables$tree_cover_1000m <- fox_variables$tree_cover_1000m * 100
fox_variables$human_fpi_1000m <- fox_variables$human_fpi_1000m * 2
head(fox_variables)
summary(fox_variables)
```
```{r}
readr::write_rds(fox_variables, paste0(procdata_wd, "/BE_BB_foxes_envir_variables_epsg3035.rds"))
```

